name: Notify Discord

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚀 New push to **main**
            📦 Repo: ${{ github.repository }}
            👤 Author: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}
            🔗 Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
